### ISSUE TITLE
Admin : Plusieurs cartes cashless par membre

### ISSUE THREAD

**Issue by jojo27888** [TiBillet/LaBoutik#13]
Rien d'urgent et facilement contournable aujourd'hui.
Avoir la possibilité d'attribuer plusieurs cartes à un membre serait utile.
Par exemple, pour les cartes primaires, dans le cadre d'une gestion fine des droits sur les appareils, les membres "responsables" de l'ensemble des POS peuvent vite se voir attribuer plusieurs cartes primaires.

**Comment by Nasjoe** [comment]
Et hop ! J'ai oublié de fermer cette issue, c'est désormais possible :
https://github.com/TiBillet/LaBoutik/commit/af8538fa4b8cef5498d85f47b58073993db2ce9e
