### ISSUE TITLE
 Pointer vers une instance de PostgreSQL

### ISSUE THREAD

**Issue by cl-parsons** [TiBillet/LaBoutik#18]
Même issue que sur TiBillet

https://github.com/TiBillet/Lespass/issues/10

**Comment by Nasjoe** [comment]
Merci !
C'est corrigé ici : 
https://github.com/TiBillet/LaBoutik/commit/a74465919ddeb157ce5c911b5175afcc335676d7

Et sur la doc : 
https://github.com/TiBillet/documentation_v2/commit/eab6a7de54656bfe588a3e2befcdc2d0f565c1ae
